// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sentiment_analytic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SentimentAnalyticClient is the client API for SentimentAnalytic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentimentAnalyticClient interface {
	AnalyzeSentiment(ctx context.Context, in *InputFile, opts ...grpc.CallOption) (*OutputFile, error)
}

type sentimentAnalyticClient struct {
	cc grpc.ClientConnInterface
}

func NewSentimentAnalyticClient(cc grpc.ClientConnInterface) SentimentAnalyticClient {
	return &sentimentAnalyticClient{cc}
}

func (c *sentimentAnalyticClient) AnalyzeSentiment(ctx context.Context, in *InputFile, opts ...grpc.CallOption) (*OutputFile, error) {
	out := new(OutputFile)
	err := c.cc.Invoke(ctx, "/SentimentAnalytic.SentimentAnalytic/AnalyzeSentiment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentimentAnalyticServer is the server API for SentimentAnalytic service.
// All implementations must embed UnimplementedSentimentAnalyticServer
// for forward compatibility
type SentimentAnalyticServer interface {
	AnalyzeSentiment(context.Context, *InputFile) (*OutputFile, error)
	mustEmbedUnimplementedSentimentAnalyticServer()
}

// UnimplementedSentimentAnalyticServer must be embedded to have forward compatible implementations.
type UnimplementedSentimentAnalyticServer struct {
}

func (UnimplementedSentimentAnalyticServer) AnalyzeSentiment(context.Context, *InputFile) (*OutputFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeSentiment not implemented")
}
func (UnimplementedSentimentAnalyticServer) mustEmbedUnimplementedSentimentAnalyticServer() {}

// UnsafeSentimentAnalyticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentimentAnalyticServer will
// result in compilation errors.
type UnsafeSentimentAnalyticServer interface {
	mustEmbedUnimplementedSentimentAnalyticServer()
}

func RegisterSentimentAnalyticServer(s grpc.ServiceRegistrar, srv SentimentAnalyticServer) {
	s.RegisterService(&SentimentAnalytic_ServiceDesc, srv)
}

func _SentimentAnalytic_AnalyzeSentiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentimentAnalyticServer).AnalyzeSentiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SentimentAnalytic.SentimentAnalytic/AnalyzeSentiment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentimentAnalyticServer).AnalyzeSentiment(ctx, req.(*InputFile))
	}
	return interceptor(ctx, in, info, handler)
}

// SentimentAnalytic_ServiceDesc is the grpc.ServiceDesc for SentimentAnalytic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentimentAnalytic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SentimentAnalytic.SentimentAnalytic",
	HandlerType: (*SentimentAnalyticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSentiment",
			Handler:    _SentimentAnalytic_AnalyzeSentiment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentiment_analytic.proto",
}
